seed_everything: 42

trainer:
  gpus: 1
  accumulate_grad_batches: 1
  precision: 32
  num_sanity_val_steps: 0
  deterministic: true
  auto_lr_find: false
  logger:
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: hw1-asr
        save_dir: lightning_logs/

model:
  model:
    class_path: src.model.ASRModel
    init_args:
      n_classes: 29
      rnn_num_layers: 2
      rnn_input_size: 352
      rnn_hidden_size: 64
      sample_rate: 16000
      n_fft: 1024
      win_length: 1024
      hop_length: 256
      n_mels: 64
  criterion:
    class_path: torch.nn.CTCLoss
    init_args:
      blank: 0
      reduction: mean
      zero_infinity: true
  optimizer_lr: 0.001

data:
  train_dataset:
    class_path: src.dataset.OverfitDataset
    init_args:
      dataset:
        class_path: src.dataset.LibrispeechDataset
        init_args:
          root: 'data/'
          url: 'train-clean-360'
      num_samples: 32
      length: 32000
  train_batch_size: 32
  train_num_workers: 1
  val_dataset:
    class_path: src.dataset.OverfitDataset
    init_args:
      dataset:
        class_path: src.dataset.LibrispeechDataset
        init_args:
          root: 'data/'
          url: 'train-clean-360'
      num_samples: 32
      length: 32
  val_batch_size: 32
  val_num_workers: 1
