seed_everything: 42

trainer:
  gpus: 1
  check_val_every_n_epoch: 1
  limit_val_batches: 1.0
  fast_dev_run: false
  accumulate_grad_batches: 4
  track_grad_norm: 2
  max_epochs: 50
  precision: 16
  num_sanity_val_steps: 2
  deterministic: false
  auto_lr_find: false
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        dirpath: checkpoints/stage1
        filename: "{epoch:03d}-{val_cer:.4f}-{val_wer:.4f}"
        monitor: "val_cer"
        mode: "min"
        save_top_k: -1
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch

model:
  model:
    class_path: src.model.ASRModel
    init_args:
      n_classes: 29
      rnn_num_layers: 3
      rnn_hidden_size: 800
      head_hidden_size: 1600
      n_mels: 128
  criterion:
    class_path: torch.nn.CTCLoss
    init_args:
      blank: 0
      reduction: mean
      zero_infinity: false
  optimizer_lr: 0.001
  n_examples: 3

data:
  train_batch_size: 32
  train_num_workers: 32
  train_dataset:
    class_path: src.dataset.PartialDataset
    init_args:
      dataset:
        class_path: src.dataset.LJSpeechDataset
        init_args:
          root: 'data/'
          transforms: src.augment.train_transforms
          spectrogram:
            class_path: torchaudio.transforms.MelSpectrogram
            init_args:
              sample_rate: 22050
              n_fft: 440
              win_length: 440
              hop_length: 220
              n_mels: 128
      start_idx: 0
      finish_idx: 12445
  val_batch_size: 32
  val_num_workers: 32
  val_dataset:
    class_path: src.dataset.PartialDataset
    init_args:
      dataset:
        class_path: src.dataset.LJSpeechDataset
        init_args:
          root: 'data/'
          transforms: src.augment.val_transforms
          spectrogram:
            class_path: torchaudio.transforms.MelSpectrogram
            init_args:
              sample_rate: 22050
              n_fft: 440
              win_length: 440
              hop_length: 220
              n_mels: 128
      start_idx: 12445
      finish_idx: 13100
  test_batch_size: 32
  test_num_workers: 32
  test_dataset:
    class_path: src.dataset.PartialDataset
    init_args:
      dataset:
        class_path: src.dataset.LJSpeechDataset
        init_args:
          root: 'data/'
          transforms: src.augment.val_transforms
          spectrogram:
            class_path: torchaudio.transforms.MelSpectrogram
            init_args:
              sample_rate: 22050
              n_fft: 440
              win_length: 440
              hop_length: 220
              n_mels: 128
      start_idx: 12445
      finish_idx: 13100

