seed_everything: 42

trainer:
  gpus: 1
  check_val_every_n_epoch: 1
  fast_dev_run: true
  accumulate_grad_batches: 1
  max_epochs: 10
  precision: 32
  num_sanity_val_steps: 2
  deterministic: true
  auto_lr_find: false

model:
  model:
    class_path: src.model.ASRModel
    init_args:
      n_classes: 29
      rnn_num_layers: 2
      rnn_input_size: 352
      rnn_hidden_size: 64
      sample_rate: 16000
      n_fft: 1024
      win_length: 1024
      hop_length: 256
      n_mels: 64
  criterion:
    class_path: torch.nn.CTCLoss
    init_args:
      blank: 0
      reduction: mean
      zero_infinity: false
  optimizer_lr: 0.001

data:
  train_root: 'data/'
  train_df_url: 'train-clean-360'
  train_batch_size: 32
  train_num_workers: 1 # TODO: fix
  val_root: 'data/'
  val_df_url: 'test-clean'
  val_batch_size: 32
  val_num_workers: 1 # TODO: fix
