seed_everything: 42

trainer:
  gpus: 1
  check_val_every_n_epoch: 1
  limit_val_batches: 4
  fast_dev_run: false
  accumulate_grad_batches: 1
  track_grad_norm: -1
  max_epochs: 50
  precision: 32
  num_sanity_val_steps: 2
  deterministic: true
  auto_lr_find: false
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: hw1-asr
      save_dir: lightning_logs/

model:
  model:
    class_path: src.model.ASRModel
    init_args:
      n_classes: 29
      rnn_num_layers: 1
      rnn_hidden_size: 1024
      n_mels: 128
  train_spectrogram:
    class_path: torchaudio.transforms.MelSpectrogram
    init_args:
      sample_rate: 22050
      n_fft: 440
      win_length: 440
      hop_length: 220
      n_mels: 128
  val_spectrogram:
    class_path: torchaudio.transforms.MelSpectrogram
    init_args:
      sample_rate: 16000
      n_fft: 320
      win_length: 320
      hop_length: 160
      n_mels: 128
  criterion:
    class_path: torch.nn.CTCLoss
    init_args:
      blank: 0
      reduction: mean
      zero_infinity: false
  optimizer_lr: 0.001
  n_examples: 3

data:
  train_batch_size: 32
  train_num_workers: 32
  train_dataset:
    class_path: src.dataset.LJSpeechDataset
    init_args:
      root: 'data/'
      transforms: src.augment.train_transforms
  val_batch_size: 32
  val_num_workers: 32
  val_dataset:
    class_path: src.dataset.LibrispeechDataset
    init_args:
      root: 'data/'
      url: 'test-clean'
      transforms: src.augment.val_transforms
